ARG PHP_VERSION=8.2
FROM php:${PHP_VERSION}-apache

# Install ImageMagick and enable its PHP Module
RUN apt-get update
RUN apt-get install -y --no-install-recommends libmagickwand-dev
RUN pecl install imagick-3.7.0
RUN docker-php-ext-enable imagick

# Install PHP Modules
RUN docker-php-ext-install pdo pdo_mysql

# Enable Apache HTTP Modules
RUN a2enmod rewrite

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
